 const data={
properties:[
  {
    id: '1',
    tag: 'For Sale',
    title: 'Modern Apartment',
    price: '100,000',
    address: 'Fifth Avenue, East-Legon',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require("./images/home1.jpg"),
    featured: true,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '2',
    tag: 'For Sale',
    title: 'Family Home',
    price: '800,000',
    address: 'Fifth Avenue, East-Legon',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require('./images/home2.jpg'),
    featured: true,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '3',
    tag: 'For Rent',
    title: 'Family Home',
    price: '900/Mo',
    address: 'coastal, Spintex',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require('./images/home3.jpg'),
    featured: true,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '4',
    tag: 'For Sale',
    title: 'Luxury Apartment',
    price: '120,000',
    address: 'East Airport',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require('./images/home4.jpg'),
    featured: true,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '5',
    tag: 'For Rent',
    title: 'Family Homes',
    price: '900/Mo',
    address: 'West Legon',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require('./images/home2.jpg'),
    featured: false,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '6',
    tag: 'For Sale',
    title: 'Luxury Apartment',
    price: '120,000',
    address: 'Sakumono',
    bedrooms: 3,
    baths: 4,
    size: 150,
    image: require('./images/home1.jpg'),
    featured: false,
    type: 'house',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '7',
    tag: 'For Sale',
    title: '1 Acre',
    price: '120,000',
    address: 'Coastal Spintex, Accra',
    bedrooms: null,
    baths: null,
    size: 180,
    image: require('./images/land1.jpg'),
    featured: false,
    type: 'land',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '8',
    tag: 'For Sale',
    title: '10 Plots',
    price: '200,000',
    address: 'East Legon',
    bedrooms: null,
    baths: null,
    size: 150,
    image: require('./images/land2.jpg'),
    featured: false,
    type: 'land',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '9',
    tag: 'For Sale',
    title: '2 Acres',
    price: '200,000',
    address: 'Coastal Spintex, Accra',
    bedrooms: null,
    baths: null,
    size: null,
    image: require('./images/land3.jpg'),
    featured: false,
    type: 'land',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
  {
    id: '10',
    tag: 'For Sale',
    title: '10 Plots',
    price: '50,000',
    address: 'Sakumono',
    bedrooms: null,
    baths: null,
    size: 150,
    image: require('./images/land4.jpg'),
    featured: false,
    type: 'land',
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
  },
]
 }

 export default data;
